# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroParte', models.CharField(max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(choices=[('UN', 'UN'), (' M ', ' M '), ('KG ', 'KG '), ('LTS', 'LTS')], default='UN', max_length=3)),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
                ('datasheet', models.CharField(blank=True, max_length=200, null=True)),
                ('EsActivo', models.BooleanField(default=True)),
                ('EsVisible', models.BooleanField(default=True)),
                ('TieneHojaDatos', models.BooleanField(default=False)),
            ],
        ),
    ]
