# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_articulo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(blank=True, default='Sin Título', max_length=200),
        ),
    ]
