# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0003_auto_20180730_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
