# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0004_auto_20180730_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default='no_image.png', upload_to='pic_folder/'),
        ),
    ]
