# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0005_auto_20180801_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='EsActivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='EsVisible',
            field=models.BooleanField(default=False),
        ),
    ]
