# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0006_auto_20180802_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='EsActivo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='EsVisible',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='TieneHojaDatos',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='image',
        ),
    ]
