# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0007_auto_20180802_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='local',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
