# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0008_articulo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='datasheet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='local',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='numeroParte',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='observation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad',
            field=models.CharField(choices=[('UN', 'UN'), (' M ', ' M '), ('KG ', 'KG '), ('LTS', 'LTS')], default='UN', max_length=4),
        ),
    ]
