# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0010_archivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
    ]
