# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0012_auto_20180803_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='archivo1',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='archivo',
            name='image',
            field=models.ImageField(default='/home/FreseniusMedicalCare/miDjangoProyecto/media/no_image.png', max_length=254, upload_to='/home/FreseniusMedicalCare/miDjangoProyecto/media'),
        ),
    ]
