# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0014_auto_20180803_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='image',
            field=models.ImageField(default='./no_image.png', max_length=254, upload_to='./'),
        ),
    ]
