# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0016_auto_20180803_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_art_pri',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
