# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0017_auto_20180803_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
