# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0018_articulo_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='local',
            new_name='SYS_local',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='observation',
        ),
        migrations.AddField(
            model_name='articulo',
            name='Fab_a_Pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Plano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Reemplazable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_EsActivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_EsVisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_Prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media'), ('Normal', 'Normal'), ('Baja', 'Baja')], default='Baja', max_length=6),
        ),
    ]
