# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0021_articulo_imagen_pri'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_Pri_Nombre',
            field=models.CharField(default='./no_image.png', max_length=250),
        ),
    ]
