# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0022_articulo_imagen_pri_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Ensayos',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Referencia1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Referencia2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Referencia3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Referencia4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Referencia5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_ESTADO',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('enEdicion', 'enEdicion'), ('Inicial', 'Inicial')], default='Inicial', max_length=8),
        ),
        migrations.AddField(
            model_name='articulo',
            name='comentario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='linea',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='modelo_NumParte',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_Prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media'), ('Normal', 'Normal'), ('Baja', 'Baja')], default='Baja', max_length=8),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_Pri_Nombre',
            field=models.CharField(default='no_image.png', max_length=250),
        ),
    ]
