# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0023_auto_20180808_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_EsVisible',
            field=models.BooleanField(default=True),
        ),
    ]
