# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0024_auto_20180808_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_Pri_Nombre',
            field=models.CharField(blank=True, default='no_image.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_pri',
            field=models.ImageField(blank=True, default='./no_image.png', upload_to='./pic_folder/'),
        ),
    ]
