# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0027_auto_20180808_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_ESTADO',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('en Edición', 'en Edición'), ('Inicial', 'Inicial')], default='Inicial', max_length=10),
        ),
    ]
