# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0030_auto_20180808_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Ensayos',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='linea',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
