# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0031_auto_20180808_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='datasheet',
        ),
    ]
