# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0035_auto_20180809_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_Prioridad',
            field=models.CharField(choices=[('5', 'Urgente'), ('4', 'Alta'), ('3', 'Media'), ('2', 'Normal'), ('1', 'Baja')], default='Baja', max_length=8),
        ),
    ]
