# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0037_auto_20180809_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_EsActivo',
            field=models.BooleanField(default=True),
        ),
    ]
