# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0038_auto_20180809_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='SYS_Prioridad',
            field=models.CharField(choices=[('5', '5_Urgente'), ('4', '4_Alta'), ('3', '3_Media'), ('2', '2_Normal'), ('1', '1_Baja')], default='1', max_length=8),
        ),
    ]
