# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0039_auto_20180809_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type title of file or image', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type_for_file', models.CharField(choices=[('image', 'Image'), ('file', 'File or Documents')], default='image', help_text='Please Choice only One Field, Image or Files', max_length=200)),
                ('field_uploaded', models.FileField(upload_to='gallery/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Gallery Entry',
                'verbose_name_plural': 'Gallery and Files',
                'ordering': ['-created'],
            },
        ),
    ]
