# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0040_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='numeroParte',
            field=models.CharField(default='ARA', max_length=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default='sin título', max_length=250),
        ),
    ]
