# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0043_auto_20180817_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='SYS_locked',
            field=models.BooleanField(default=False),
        ),
    ]
