# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repuestos', '0046_auto_20180830_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='SYS_ApprovedByAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_Approver_Notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_RevisedByAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_Reviser_Notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_ESTADO',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Revisado', 'Revisado'), ('enRevision', 'enRevisión'), ('enEdicion', 'en Edición'), ('Inicial', 'Inicial')], default='Inicial', max_length=10),
        ),
    ]
