# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0047_auto_20180904_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Referencia1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia3',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia4',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Referencia5',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='linea',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='modelo_NumParte',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
