# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0048_auto_20180904_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='SYS_lastESTADO',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Revisado', 'Revisado'), ('enRevision', 'enRevisión'), ('enEdicion', 'en Edición'), ('Inicial', 'Inicial')], default='Inicial', max_length=10),
        ),
        migrations.AddField(
            model_name='articulo',
            name='SYS_lastModif_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
