# Generated by Django 2.1.1 on 2018-09-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0050_auto_20180910_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Fab_a_Pedido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Plano',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Reemplazable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_ApprovedByAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_RevisedByAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_dataEntryAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='SYS_locked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
