# Generated by Django 2.1.1 on 2018-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0051_auto_20180910_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='SYS_EsOBSOLETO',
            field=models.BooleanField(default=False),
        ),
    ]
